### ISSUE TITLE
how to test danceTrack

### ISSUE THREAD

**Issue by xifen523** [NII-Satoh-Lab/MOT_FCG#2]
How to run a test set of danceTrack data

**Comment by agirbau** [comment]
Hello!
Try:
```python src/fcg_tracking.py --gt $YOUR_PATH_TO_DATASETS/dancetrack --dataset dancetrack --mode test --detector YOLOX --reid SBS --iou --spatial --w_tracklet 6 --w_fuse 3 --max_prop 40```
